// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: medelanden.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ProducerTs    uint64                 `protobuf:"varint,3,opt,name=producer_ts,json=producerTs,proto3" json:"producer_ts,omitempty"`
	DedupKey      string                 `protobuf:"bytes,4,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	MsgId         string                 `protobuf:"bytes,5,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	NodeSeq       uint64                 `protobuf:"varint,6,opt,name=node_seq,json=nodeSeq,proto3" json:"node_seq,omitempty"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Late          bool                   `protobuf:"varint,8,opt,name=late,proto3" json:"late,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_medelanden_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Msg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Msg) GetProducerTs() uint64 {
	if x != nil {
		return x.ProducerTs
	}
	return 0
}

func (x *Msg) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *Msg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Msg) GetNodeSeq() uint64 {
	if x != nil {
		return x.NodeSeq
	}
	return 0
}

func (x *Msg) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Msg) GetLate() bool {
	if x != nil {
		return x.Late
	}
	return false
}

type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PeerAddr      string                 `protobuf:"bytes,2,opt,name=peer_addr,json=peerAddr,proto3" json:"peer_addr,omitempty"`
	Peers         map[string]string      `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // nodeID -> peerAddr
	StreamDigests []*StreamDigestProto   `protobuf:"bytes,4,rep,name=stream_digests,json=streamDigests,proto3" json:"stream_digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_medelanden_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{1}
}

func (x *GossipRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GossipRequest) GetPeerAddr() string {
	if x != nil {
		return x.PeerAddr
	}
	return ""
}

func (x *GossipRequest) GetPeers() map[string]string {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *GossipRequest) GetStreamDigests() []*StreamDigestProto {
	if x != nil {
		return x.StreamDigests
	}
	return nil
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PeerAddr      string                 `protobuf:"bytes,2,opt,name=peer_addr,json=peerAddr,proto3" json:"peer_addr,omitempty"`
	Peers         map[string]string      `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StreamDigests []*StreamDigestProto   `protobuf:"bytes,4,rep,name=stream_digests,json=streamDigests,proto3" json:"stream_digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_medelanden_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{2}
}

func (x *GossipResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GossipResponse) GetPeerAddr() string {
	if x != nil {
		return x.PeerAddr
	}
	return ""
}

func (x *GossipResponse) GetPeers() map[string]string {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *GossipResponse) GetStreamDigests() []*StreamDigestProto {
	if x != nil {
		return x.StreamDigests
	}
	return nil
}

type StreamDigestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MaxSeq        uint64                 `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	MaxTs         uint64                 `protobuf:"varint,4,opt,name=max_ts,json=maxTs,proto3" json:"max_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDigestProto) Reset() {
	*x = StreamDigestProto{}
	mi := &file_medelanden_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDigestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDigestProto) ProtoMessage() {}

func (x *StreamDigestProto) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDigestProto.ProtoReflect.Descriptor instead.
func (*StreamDigestProto) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{3}
}

func (x *StreamDigestProto) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *StreamDigestProto) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StreamDigestProto) GetMaxSeq() uint64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *StreamDigestProto) GetMaxTs() uint64 {
	if x != nil {
		return x.MaxTs
	}
	return 0
}

type DigestRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	NodeId        string                        `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Digests       map[string]*StreamDigestProto `protobuf:"bytes,2,rep,name=digests,proto3" json:"digests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // stream name -> digest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestRequest) Reset() {
	*x = DigestRequest{}
	mi := &file_medelanden_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestRequest) ProtoMessage() {}

func (x *DigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestRequest.ProtoReflect.Descriptor instead.
func (*DigestRequest) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{4}
}

func (x *DigestRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DigestRequest) GetDigests() map[string]*StreamDigestProto {
	if x != nil {
		return x.Digests
	}
	return nil
}

type DigestResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	NodeId        string                        `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Digests       map[string]*StreamDigestProto `protobuf:"bytes,2,rep,name=digests,proto3" json:"digests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestResponse) Reset() {
	*x = DigestResponse{}
	mi := &file_medelanden_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestResponse) ProtoMessage() {}

func (x *DigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestResponse.ProtoReflect.Descriptor instead.
func (*DigestResponse) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{5}
}

func (x *DigestResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DigestResponse) GetDigests() map[string]*StreamDigestProto {
	if x != nil {
		return x.Digests
	}
	return nil
}

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	StartSeq      uint64                 `protobuf:"varint,2,opt,name=start_seq,json=startSeq,proto3" json:"start_seq,omitempty"`
	EndSeq        uint64                 `protobuf:"varint,3,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_medelanden_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{6}
}

func (x *PullRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *PullRequest) GetStartSeq() uint64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

func (x *PullRequest) GetEndSeq() uint64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

func (x *PullRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Messages      []*Msg                 `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_medelanden_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{7}
}

func (x *PullResponse) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *PullResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PullResponse) GetMessages() []*Msg {
	if x != nil {
		return x.Messages
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_medelanden_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{8}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_medelanden_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_medelanden_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_medelanden_proto_rawDescGZIP(), []int{9}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_medelanden_proto protoreflect.FileDescriptor

const file_medelanden_proto_rawDesc = "" +
	"\n" +
	"\x10medelanden.proto\x12\n" +
	"medelanden\"\xd6\x01\n" +
	"\x03Msg\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1f\n" +
	"\vproducer_ts\x18\x03 \x01(\x04R\n" +
	"producerTs\x12\x1b\n" +
	"\tdedup_key\x18\x04 \x01(\tR\bdedupKey\x12\x15\n" +
	"\x06msg_id\x18\x05 \x01(\tR\x05msgId\x12\x19\n" +
	"\bnode_seq\x18\x06 \x01(\x04R\anodeSeq\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04late\x18\b \x01(\bR\x04late\"\x81\x02\n" +
	"\rGossipRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tpeer_addr\x18\x02 \x01(\tR\bpeerAddr\x12:\n" +
	"\x05peers\x18\x03 \x03(\v2$.medelanden.GossipRequest.PeersEntryR\x05peers\x12D\n" +
	"\x0estream_digests\x18\x04 \x03(\v2\x1d.medelanden.StreamDigestProtoR\rstreamDigests\x1a8\n" +
	"\n" +
	"PeersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x0eGossipResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tpeer_addr\x18\x02 \x01(\tR\bpeerAddr\x12;\n" +
	"\x05peers\x18\x03 \x03(\v2%.medelanden.GossipResponse.PeersEntryR\x05peers\x12D\n" +
	"\x0estream_digests\x18\x04 \x03(\v2\x1d.medelanden.StreamDigestProtoR\rstreamDigests\x1a8\n" +
	"\n" +
	"PeersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x11StreamDigestProto\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x17\n" +
	"\amax_seq\x18\x03 \x01(\x04R\x06maxSeq\x12\x15\n" +
	"\x06max_ts\x18\x04 \x01(\x04R\x05maxTs\"\xc5\x01\n" +
	"\rDigestRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12@\n" +
	"\adigests\x18\x02 \x03(\v2&.medelanden.DigestRequest.DigestsEntryR\adigests\x1aY\n" +
	"\fDigestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.medelanden.StreamDigestProtoR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x0eDigestResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12A\n" +
	"\adigests\x18\x02 \x03(\v2'.medelanden.DigestResponse.DigestsEntryR\adigests\x1aY\n" +
	"\fDigestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.medelanden.StreamDigestProtoR\x05value:\x028\x01\"q\n" +
	"\vPullRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x1b\n" +
	"\tstart_seq\x18\x02 \x01(\x04R\bstartSeq\x12\x17\n" +
	"\aend_seq\x18\x03 \x01(\x04R\x06endSeq\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"l\n" +
	"\fPullResponse\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12+\n" +
	"\bmessages\x18\x03 \x03(\v2\x0f.medelanden.MsgR\bmessages\"\r\n" +
	"\vPingRequest\"'\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId2\x95\x02\n" +
	"\vPeerService\x12?\n" +
	"\x06Gossip\x12\x19.medelanden.GossipRequest\x1a\x1a.medelanden.GossipResponse\x12G\n" +
	"\x0eExchangeDigest\x12\x19.medelanden.DigestRequest\x1a\x1a.medelanden.DigestResponse\x12A\n" +
	"\fPullMessages\x12\x17.medelanden.PullRequest\x1a\x18.medelanden.PullResponse\x129\n" +
	"\x04Ping\x12\x17.medelanden.PingRequest\x1a\x18.medelanden.PingResponseB\x15Z\x13medelanden/proto/pbb\x06proto3"

var (
	file_medelanden_proto_rawDescOnce sync.Once
	file_medelanden_proto_rawDescData []byte
)

func file_medelanden_proto_rawDescGZIP() []byte {
	file_medelanden_proto_rawDescOnce.Do(func() {
		file_medelanden_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_medelanden_proto_rawDesc), len(file_medelanden_proto_rawDesc)))
	})
	return file_medelanden_proto_rawDescData
}

var file_medelanden_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_medelanden_proto_goTypes = []any{
	(*Msg)(nil),               // 0: medelanden.Msg
	(*GossipRequest)(nil),     // 1: medelanden.GossipRequest
	(*GossipResponse)(nil),    // 2: medelanden.GossipResponse
	(*StreamDigestProto)(nil), // 3: medelanden.StreamDigestProto
	(*DigestRequest)(nil),     // 4: medelanden.DigestRequest
	(*DigestResponse)(nil),    // 5: medelanden.DigestResponse
	(*PullRequest)(nil),       // 6: medelanden.PullRequest
	(*PullResponse)(nil),      // 7: medelanden.PullResponse
	(*PingRequest)(nil),       // 8: medelanden.PingRequest
	(*PingResponse)(nil),      // 9: medelanden.PingResponse
	nil,                       // 10: medelanden.GossipRequest.PeersEntry
	nil,                       // 11: medelanden.GossipResponse.PeersEntry
	nil,                       // 12: medelanden.DigestRequest.DigestsEntry
	nil,                       // 13: medelanden.DigestResponse.DigestsEntry
}
var file_medelanden_proto_depIdxs = []int32{
	10, // 0: medelanden.GossipRequest.peers:type_name -> medelanden.GossipRequest.PeersEntry
	3,  // 1: medelanden.GossipRequest.stream_digests:type_name -> medelanden.StreamDigestProto
	11, // 2: medelanden.GossipResponse.peers:type_name -> medelanden.GossipResponse.PeersEntry
	3,  // 3: medelanden.GossipResponse.stream_digests:type_name -> medelanden.StreamDigestProto
	12, // 4: medelanden.DigestRequest.digests:type_name -> medelanden.DigestRequest.DigestsEntry
	13, // 5: medelanden.DigestResponse.digests:type_name -> medelanden.DigestResponse.DigestsEntry
	0,  // 6: medelanden.PullResponse.messages:type_name -> medelanden.Msg
	3,  // 7: medelanden.DigestRequest.DigestsEntry.value:type_name -> medelanden.StreamDigestProto
	3,  // 8: medelanden.DigestResponse.DigestsEntry.value:type_name -> medelanden.StreamDigestProto
	1,  // 9: medelanden.PeerService.Gossip:input_type -> medelanden.GossipRequest
	4,  // 10: medelanden.PeerService.ExchangeDigest:input_type -> medelanden.DigestRequest
	6,  // 11: medelanden.PeerService.PullMessages:input_type -> medelanden.PullRequest
	8,  // 12: medelanden.PeerService.Ping:input_type -> medelanden.PingRequest
	2,  // 13: medelanden.PeerService.Gossip:output_type -> medelanden.GossipResponse
	5,  // 14: medelanden.PeerService.ExchangeDigest:output_type -> medelanden.DigestResponse
	7,  // 15: medelanden.PeerService.PullMessages:output_type -> medelanden.PullResponse
	9,  // 16: medelanden.PeerService.Ping:output_type -> medelanden.PingResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_medelanden_proto_init() }
func file_medelanden_proto_init() {
	if File_medelanden_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_medelanden_proto_rawDesc), len(file_medelanden_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medelanden_proto_goTypes,
		DependencyIndexes: file_medelanden_proto_depIdxs,
		MessageInfos:      file_medelanden_proto_msgTypes,
	}.Build()
	File_medelanden_proto = out.File
	file_medelanden_proto_goTypes = nil
	file_medelanden_proto_depIdxs = nil
}
